service: cloudwatch-logs

plugins:
 - serverless-pseudo-parameters
 - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  versionFunctions: false
  
functions:
  ship-logs-to-fluentd:
    handler: functions/ship-logs/handler.handler
    description: Sends CloudWatch logs to fluentd
    memorySize: 128
    environment:
      logstash_host: logs.danquack.dev

resources:
  Resources:
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::Join:
            - ""
            - - "Ref" : "ShipDashlogsDashtoDashfluentdLambdaFunction"
        Principal: logs.#{AWS::Region}.amazonaws.com
